version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    env_file:
      - ./db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 5050:80
    env_file:
      - ./db.env
    depends_on:
      - postgres
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_data_config:/data/configdb
volumes:
  postgres_data:
  mongodb_data:
  mongodb_data_config:
